[_]
name = "foobarbaz"
schema-version = "0.2"
id = "heroku/fir/fun"
[[_.licenses]]
type = "MIT"
[_.metadata]
pipeline = "rd-fir-pipeline-0"
[[io.buildpacks.group]]
uri = "gcr.io/paketo-buildpacks/nodejs"
